; Miri build bundle for integrated firmware builds.

[env:miri_esp32]
extends = env:esp32dev
custom_usermods = miri miri_color_sphere
build_flags = ${env:esp32dev.build_flags}
  -D USERMOD_MIRI
  -D USERMOD_MIRI_TEMP_SENSOR
  -D USERMOD_MIRI_FUSE_MONITOR
  -D USERMOD_MIRI_PWM
  -D USERMOD_MIRI_BOARD_IICIE
  -D USERMOD_MIRI_COLOR_SPHERE
  -D WLED_RELEASE_NAME=\"Miri\"
