; Miri build bundle for integrated firmware builds.

[env:miri_esp32]
extends = env:esp32dev
custom_usermods = miri miri_color_sphere usermod_ui
build_flags = ${env:esp32dev.build_flags}
  -D USERMOD_MIRI
  -D USERMOD_MIRI_TEMP_SENSOR
  -D USERMOD_MIRI_FUSE_MONITOR
  -D USERMOD_MIRI_PWM
  -D USERMOD_MIRI_BOARD_IICIE
  -D USERMOD_MIRI_COLOR_SPHERE
  -D USERMOD_UI
  -D WLED_RELEASE_NAME=\"Miri\"
  -D HW_PIN_SDA=9
  -D HW_PIN_SCL=10
  -D MIRI_I2C_SDA=9
  -D MIRI_I2C_SCL=10
