Import("env")
import gzip
import hashlib
import json
import os
import subprocess
import sys
from pathlib import Path

PROJECT_DIR = Path(env["PROJECT_DIR"])
USERMODS_DIR = PROJECT_DIR / "usermods"
OUT_DIR = PROJECT_DIR / "usermods" / "ui_wrapper"
HEADER_PATH = OUT_DIR / "generated_ui_bundle.h"
HASH_PATH = OUT_DIR / ".bundle_inputs_hash"

RUNALL = """
window.WLEDUI._runAll = function (idoc) {
  Object.entries(window.WLEDUI._modules).forEach(function (entry) {
    var name = entry[0], init = entry[1];
    var container = idoc.querySelector('[data-usermod="' + name + '"]');
    if (!container) {
      container = idoc.createElement('div');
      container.setAttribute('data-usermod', name);
      idoc.body.appendChild(container);
    }
    try { init(container, idoc); } catch (e) { console.error('WLEDUI[' + name + '] failed:', e); }
  });
};
"""


def cpp_defines():
    out = []
    for d in env.get("CPPDEFINES", []):
        out.append(d[0] if isinstance(d, tuple) else str(d))
    return out


def define_to_folder(define):
    if define.startswith("USERMOD_"):
        return define[8:].lower()
    return define.lower()


def discover_modules():
    modules = []
    for define in sorted(cpp_defines()):
        if not define.startswith("USERMOD_"):
            continue
        folder = define_to_folder(define)
        ui_js = USERMODS_DIR / folder / "ui.js"
        if ui_js.is_file():
            modules.append((folder, ui_js))
    return modules


def syntax_check(path):
    node = env.get("PYTHONEXE", "node")
    # Prefer system node (WLED build already requires it for cdata.js)
    for candidate in ("node", node):
        try:
            subprocess.run(
                [candidate, "--check", str(path)],
                check=True,
                capture_output=True,
                text=True,
            )
            return
        except (subprocess.CalledProcessError, FileNotFoundError):
            continue
    raise RuntimeError("bundle_ui.py: node not found — required for ui.js syntax check")


def minify_js(source):
    script = r"""
const { minify } = require('terser');
let data = '';
process.stdin.on('data', c => { data += c; });
process.stdin.on('end', async () => {
  try {
    const r = await minify(data, { compress: true, mangle: false });
    process.stdout.write(r.code || data);
  } catch (e) {
    process.stdout.write(data);
  }
});
"""
    try:
        result = subprocess.run(
            ["node", "-e", script],
            input=source,
            capture_output=True,
            text=True,
            cwd=str(PROJECT_DIR),
            check=True,
        )
        return result.stdout or source
    except (subprocess.CalledProcessError, FileNotFoundError):
        return source


def wrap_module(name, body):
    safe = json.dumps(name)
    return (
        f"window.WLEDUI._modules[{safe}] = (function () {{\n"
        f"{body}\n"
        f"  return init;\n"
        f"}})();\n"
    )


def build_bundle_js(modules):
    parts = ["window.WLEDUI = window.WLEDUI || { _modules: {} };\n"]
    for name, path in modules:
        syntax_check(path)
        body = path.read_text(encoding="utf-8")
        parts.append(wrap_module(name, body))
    parts.append(RUNALL)
    return minify_js("".join(parts))


def format_progmem(data):
    lines = []
    for i in range(0, len(data), 16):
        chunk = data[i : i + 16]
        lines.append("  " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    return "\n".join(lines)


def inputs_hash(modules, bundle_js):
    h = hashlib.sha256()
    h.update(bundle_js.encode("utf-8"))
    for name, path in modules:
        h.update(name.encode())
        h.update(path.read_bytes())
    for d in sorted(cpp_defines()):
        if d.startswith("USERMOD_"):
            h.update(d.encode())
    return h.hexdigest()


def write_header(gz_data, raw_len):
    content = (
        "#pragma once\n"
        "// Auto-generated by tools/bundle_ui.py — do not edit.\n"
        f"const uint8_t UI_BUNDLE[] PROGMEM = {{\n"
        f"{format_progmem(gz_data)}\n"
        f"}};\n"
        f"const size_t UI_BUNDLE_LENGTH = {len(gz_data)};\n"
        f"// Uncompressed bundle size: {raw_len} bytes\n"
    )
    HEADER_PATH.write_text(content, encoding="utf-8")


modules = discover_modules()
bundle_js = build_bundle_js(modules)
digest = inputs_hash(modules, bundle_js)

if HASH_PATH.is_file() and HASH_PATH.read_text(encoding="utf-8").strip() == digest:
    print("bundle_ui.py: unchanged — skipping regeneration")
else:
    gz_data = gzip.compress(bundle_js.encode("utf-8"), compresslevel=9)
    write_header(gz_data, len(bundle_js))
    HASH_PATH.write_text(digest, encoding="utf-8")
    names = ", ".join(m[0] for m in modules) or "(none)"
    print(
        f"bundle_ui.py: bundled [{names}] — "
        f"{len(bundle_js)} B raw, {len(gz_data)} B gzip → generated_ui_bundle.h"
    )
